config/routes.rb
Rails.application.routes.draw do
  
  # sign in with Facebook
  get '/auth/facebook/callback' => 'sessions#facebook'
  get 'auth/failure', to: redirect('/')
  
  root 'sessions#welcome'

  # home_path
  get '/home' => 'sessions#home'

  # login_path
  get '/login' => 'sessions#new'

  # create_path
  post '/login' => 'sessions#login'

  # logout_path
  get '/logout' => 'sessions#logout'
 
  resources :crews
  
  # ships_fastest_path
  get '/ships/fastest' => 'ships#fastest'
  
  # ship_assignments, ship_assignment, new_ship_assignment, edit_ship_assignment, etc
  resources :ships do
    resources :assignments
  end

  resources :assignments

  get '/404', :to => 'errors#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :ship
    belongs_to :crew
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    before_action :require_login
    before_action :set_ship, only: [:edit, :update]
    before_action :set_assignment, only: [:show, :edit, :update]

    def index
        @assignments = Assignment.all
        if params[:ship_id]
            @assignment = Assignment.new(ship_id: params[:ship_id])
        else
            @assignment = Assignment.new
        end
    end

    def new
        @assignment = Assignment.new(ship_id: params[:ship_id])
    end

    def create
        @assignment = Assignment.new(assignment_params)
        if @assignment.save
            respond_to do |format|
                format.json { render json: @assignment }
                format.html { render :show }
            end
        else
            redirect_to new_assignment_path, alert: "Error: #{@assignment.errors.full_messages.join(", ")}"
        end
    end

    def show
        if @assignment
            respond_to do |format|
                format.html { render :show }
                format.json { render json: @assignment}
            end
        else
            redirect_to new_assignment_path, notice: "That ship does not currently have an assignment, create one here."
        end
    end

    def edit
    end

    def update
        if @assignment.update(assignment_params)
            redirect_to ship_assignment_path(params[:assignment][:ship_id])
        else
            redirect_to edit_ship_assignment_path(@assignment), alert: "Error: #{@assignment.errors.full_messages.join(", ")}"
        end
    end

    def destroy
        Assignment.find_by(:id => params[:id]).destroy
        flash[:notice] = "Assignment deleted."
        redirect_to assignments_path
    end

    
    private

    def assignment_params
        params.require(:assignment).permit(:name, :description, :crew_id, :ship_id)
    end
    
    def set_assignment
        @assignment = Assignment.find_by(:ship_id => params[:ship_id], :id => params[:id])
    end

    def set_ship
        @ship = Ship.find_by(id: params[:ship_id])
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for([@ship, @assignment]) do |f| %>
    
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name %><br>
    
    <strong><%= f.label :description %></strong>
    <%= f.text_field :description %><br></br>
    
    <strong><%= f.label :ship_id %></strong><br>
    <!-- <%= f.collection_check_boxes :ship_id, Ship.all, :id, :name %><br></br> -->
    <%= f.select(:ship_id) do %>
        <%= options_from_collection_for_select(Ship.all, :id, :name, :selected => @assignment.ship_id) %>
    <% end %>

    <br></br>
    <strong><%= f.label :crew_id %></strong><br>
    <!--<%= f.collection_check_boxes :crew_id, Crew.all, :id, :name %><br> -->
    <%= f.select(:crew_id) do %>
        <%= options_from_collection_for_select(Crew.all, :id, :name, :selected => @assignment.crew_id) %>
    <% end %>

    <br></br>
    <!-- <%= f.submit %> -->
    <button type="submit" name="commit" value="Create Assignment">Create Assignment</button>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit this assignment</h1>

<%= render 'form' %>

app/views/assignments/index.html.erb
<h1>All assignments for all ships:</h1>
<ul id="assignmentList">
<% @assignments.each do |a| %>
    <li><%= a.crew.formal_title %> is <%= link_to "assigned", ship_assignment_path(a.ship, a) %> to the <%= a.ship.name %>.</li>
<% end %>
</ul>
<br>

<h2>Create new assignment:</h2>
<%= render 'form' %>

<script>window.onload = postAssignment();</script>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h2>Assignment Information</h2>

Assignment Name, Number: <%= @assignment.name %>, #<%= @assignment.id %><br>
Assignment Description: <%= @assignment.description %><br>
Assigned Ship: #<%= @assignment.ship_id %> - <%= @assignment.ship.name %><br>
Assigned Crew: #<%= @assignment.crew_id %> - <%= @assignment.crew.name %><br>
<br></br>
<p><%= link_to "Edit this assignment", edit_assignment_path(@assignment.id) %></p>
<p><%= link_to "Delete", @assignment, method: :delete, data: { confirm: "Confirm Deleting?" } %></p>