config/routes.rb
Rails.application.routes.draw do
  
  # sign in with Facebook
  get '/auth/facebook/callback' => 'sessions#facebook'
  get 'auth/failure', to: redirect('/')
  
  root 'sessions#welcome'

  # home_path
  get '/home' => 'sessions#home'

  # login_path
  get '/login' => 'sessions#new'

  # create_path
  post '/login' => 'sessions#login'

  # logout_path
  get '/logout' => 'sessions#logout'
 
  resources :crews
  
  # ships_fastest_path
  get '/ships/fastest' => 'ships#fastest'
  
  # ship_assignments, ship_assignment, new_ship_assignment, edit_ship_assignment, etc
  resources :ships do
    resources :assignments
  end

  resources :assignments

  get '/404', :to => 'errors#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ship.rb
class Ship < ApplicationRecord
    has_many :assignments, dependent: :destroy
    has_many :crews, through: :assignments

    validates_presence_of :name

    # return the current fastest ship
    def self.fastest
        order(:warp_factor).last
    end

    def assignments_attributes=(assignments_attributes)
        assignments_attributes.values.each do |assignment_attributes|
            if assignment_attributes[:crew_id] != ""
                assignment = Assignment.find_or_create_by(assignment_attributes)
                if !self.assignments.include?(assignment)
                    self.assignments.build(assignment_attributes)
                end
            end
        end
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
    before_action :require_login
    before_action :set_ship, only: [:show, :edit, :update, :destroy]    

    def index
        @ships = Ship.all
        render json: @ships
        # respond_to do |format|
        #     format.json { render json: @ships }
        #     format.html { render :index }
        # end
    end

    def new
        @ship = Ship.new
    end

    def create
        @ship = Ship.new(ship_params)
        if @ship.save
            redirect_to ship_path(@ship)
        else
            redirect_to new_ship_path(@ship), error: "Error: #{@ship.errors.full_messages.join(", ")}"
        end
    end

    def show
        @ship = Ship.find_by_id(params[:id])
        @crews = @ship.crews
        # render json: @ship
        respond_to do |format|
            format.json { render json: @ship }
            format.html { render :show }
        end
    end

    def edit
    end

    def update
        if @ship.update(ship_params)
            redirect_to ship_path(@ship)
        else
            redirect_to edit_ship_path(@ship), error: "Error: #{@ship.errors.full_messages.join(", ")}"
        end
    end

    def fastest
        @ship = Ship.fastest
    end

    def destroy
        @ship.destroy
        flash[:notice] = "Ship record deleted."
        redirect_to ships_path
    end

    
    private

    def ship_params
        params.require(:ship).permit(:name, :type_class, :warp_factor, :complement, :note, :assignment_ids => [], :assignments_attributes=>[:name, :description, :crew_id, :ship_id])
    end

    def set_ship
        @ship = Ship.find_by(id: params[:id])
    end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/edit.html.erb
<h1>Edit Ship Form</h1>

<%= form_for @ship do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :type_class %>
    <%= f.text_field :type_class %><br>
    <%= f.label :warp_factor %>
    <%= f.number_field :warp_factor, class: :text_field, step: :any %><br>
    <%= f.label :complement %>
    <%= f.number_field :complement %><br>
    <%= f.label :note %>
    <%= f.text_area :note %><br><br>
    <br></br>
    <%= f.submit %>
<% end %>

<% if @ship.errors.any? %>
  <div class="error_explanation">
    <% @ship.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

app/views/ships/fastest.html.erb
<h1>This is currently the fastest ship in the fleet:</h1>

<p>Name: <%= @ship.name %></p>
<p>Class: <%= @ship.type_class %></p>
<p>Max warp factor: <%= @ship.warp_factor %></p>
<p>Crew Complement Size: <%= @ship.complement %></p>
<p>Notes: <%= @ship.note if @ship.note %></p>

app/views/ships/index.html.erb
<h2>The Fleet</h2>
<div class="content">
    <ul id="ships_list">
    <% @ships.each do |s| %>
        <li><%= link_to "#{s.name}", ship_path(s) %></li>
    <% end %>
    </ul>
</div>

<div class="sidebar">
    <h3>Menu</h3>
    <ul>
        <li><%= link_to "What's the fastest ship right now?", ships_fastest_path %></li>
        <li><%= link_to "Add a new ship", new_ship_path %></li>
    </ul>
</div>

app/views/ships/new.html.erb
<h1>New Ship Form</h1>

<%= form_for @ship do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :type_class %>
    <%= f.text_field :type_class %><br>
    <%= f.label :warp_factor %>
    <%= f.number_field :warp_factor, class: :text_field, step: :any %><br>
    <%= f.label :complement %>
    <%= f.number_field :complement %><br>
    <%= f.label :note %>
    <%= f.text_area :note %><br></br>
    
    <p>Create Assignment?</p>
    <%= f.fields_for :assignments, @ship.assignments.build do |a| %>
        
        <p>Select a crew person:
        <%= select_tag 'ship[assignments_attributes][0][crew_id]', content_tag(:option,'select one...',:value=>"")+options_from_collection_for_select(Crew.all, :id, :name) %></p>

        <%= a.hidden_field :ship_id, value: @ship.id %>

        <%= a.label :name, "Assignment Name" %>
        <%= a.text_field :name %><br>
        <%= a.label :description %>
        <%= a.text_field :description %>
    <% end %>
    <br>
    <%= f.submit %>
<% end %>

<% if @ship.errors.any? %>
  <div class="error_explanation">
    <% @ship.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

app/views/ships/show.html.erb
<h1>Ship Information</h1>

<h2><%= @ship.name %></h2>
<ul>
    <li>Type/class: <%= @ship.type_class %></li>
    <li>Warp Factor: <%= @ship.warp_factor %></li>
    <li>Crew Complement Size: <%= @ship.complement %></li>
    <li>Notes: <%= @ship.note if @ship.note %></li>
</ul><br>

<h3>Current crew</h3>
<ul>
<% @crews.each do |c| %>
    <% a = Assignment.find_by(:ship_id => @ship.id, :crew_id => c.id) %>
    <li><%= link_to "#{c.formal_title}", ship_assignment_path(@ship, a) %></li>
<% end %>
</ul>
<br>
<p><%= link_to "Add assignment", new_ship_assignment_path(@ship) %></p>
<br></br>


<p><%= link_to "Edit this ship's info", edit_ship_path(@ship) %> | <%= link_to "Delete Ship", @ship, method: :delete, data: { confirm: "Confirm Deleting?" }  %></p>